# Generated by Django 5.1.2 on 2024-10-25 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 13, 50, 4, 866222)),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
