# Generated by Django 5.1.2 on 2024-10-25 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_user_join_date_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 13, 52, 50, 168848)),
        ),
    ]
