# Generated by Django 5.1.2 on 2024-10-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_barang_alter_user_join_date_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], default='makanan', max_length=20),
        ),
        migrations.AddField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('PCS', 'pcs'), ('BOX', 'box'), ('KG', 'kg')], default='PCS', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 2, 7, 41, 581298)),
        ),
    ]
