# Generated by Django 5.1.2 on 2024-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0007_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='kode_barang',
        ),
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('--kategori--', '--kategori--'), ('makanan', 'Makanan'), ('minuman', 'Minuman')], default='--satuan--', max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('--satuan--', '--satuan--'), ('PCS', 'pcs'), ('BOX', 'box'), ('KG', 'kg')], default='--satuan--', max_length=20),
        ),
    ]
