# Generated by Django 5.1.2 on 2024-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_remove_barang_kode_barang_alter_barang_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='desc',
        ),
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('Makanan', 'makanan'), ('Minuman', 'minuman')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('Pcs', 'pcs'), ('Pack', 'pack'), ('Box', 'box')], default='', max_length=20),
        ),
    ]
