# Generated by Django 5.1.2 on 2024-11-23 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_remove_barang_desc_alter_barang_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_barang_masuk', models.PositiveIntegerField(default=0)),
                ('nama_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.barang')),
            ],
        ),
    ]
