# Generated by Django 5.1.2 on 2024-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_barangmasuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('Makanan', 'makanan'), ('Minuman', 'minuman')], max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('Pcs', 'pcs'), ('Pack', 'pack'), ('Box', 'box')], max_length=20),
        ),
    ]
