# Generated by Django 5.1.2 on 2024-11-23 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_alter_barang_kategori_alter_barang_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmasuk',
            name='tanggal_masuk',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
