# Generated by Django 5.1.2 on 2024-11-23 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_alter_barangmasuk_tanggal_masuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_keluar', models.DateField(default=django.utils.timezone.now)),
                ('total_barang_keluar', models.PositiveIntegerField(default=0)),
                ('nama_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.barang')),
            ],
        ),
    ]
