# Generated by Django 5.1.2 on 2024-12-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_barangkeluar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangkeluar',
            old_name='nama_barang',
            new_name='barang',
        ),
        migrations.RenameField(
            model_name='barangmasuk',
            old_name='nama_barang',
            new_name='barang',
        ),
    ]
